// <auto-generated />
using System;
using JassApp.DataAccess.DbContexts.Contexts.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JassApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808141218_JassTeamSpieler3")]
    partial class JassTeamSpieler3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JassApp.DataAccess.Tables.CoiffeurSpielrundeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoiffeurSpielrundeTyp")
                        .HasColumnType("int");

                    b.Property<DateTime>("GestartetAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Punktewert")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoiffeurSpielrundeTable", (string)null);
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.JassTeamSpielerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IstStartSpieler")
                        .HasColumnType("bit");

                    b.Property<int>("JassTeamId")
                        .HasColumnType("int");

                    b.Property<int>("SpielerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JassTeamId");

                    b.HasIndex("SpielerId");

                    b.ToTable("JassTeamSpielerTable", (string)null);
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.JassTeamTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoiffeurSpielrundeId")
                        .HasColumnType("int");

                    b.Property<int>("JassTeamSpieler1Id")
                        .HasColumnType("int");

                    b.Property<int>("JassTeamSpieler2Id")
                        .HasColumnType("int");

                    b.Property<int>("JassTeamTyp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoiffeurSpielrundeId");

                    b.HasIndex("JassTeamSpieler1Id");

                    b.HasIndex("JassTeamSpieler2Id");

                    b.ToTable("JassTeamTable", (string)null);
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.SpielerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpielerTable", (string)null);
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.TrumpfrundeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoiffeurSpielrundeId")
                        .HasColumnType("int");

                    b.Property<int>("PunkteModifikator")
                        .HasColumnType("int");

                    b.Property<string>("ResultatTeam1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResultatTeam2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TrumpfTyp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoiffeurSpielrundeId");

                    b.ToTable("TrumpfrundeTable", (string)null);
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.JassTeamSpielerTable", b =>
                {
                    b.HasOne("JassApp.DataAccess.Tables.JassTeamTable", "JassTeam")
                        .WithMany()
                        .HasForeignKey("JassTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JassApp.DataAccess.Tables.SpielerTable", "Spieler")
                        .WithMany()
                        .HasForeignKey("SpielerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JassTeam");

                    b.Navigation("Spieler");
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.JassTeamTable", b =>
                {
                    b.HasOne("JassApp.DataAccess.Tables.CoiffeurSpielrundeTable", null)
                        .WithMany("JassTeams")
                        .HasForeignKey("CoiffeurSpielrundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JassApp.DataAccess.Tables.JassTeamSpielerTable", "JassTeamSpieler1")
                        .WithMany()
                        .HasForeignKey("JassTeamSpieler1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JassApp.DataAccess.Tables.JassTeamSpielerTable", "JassTeamSpieler2")
                        .WithMany()
                        .HasForeignKey("JassTeamSpieler2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JassTeamSpieler1");

                    b.Navigation("JassTeamSpieler2");
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.TrumpfrundeTable", b =>
                {
                    b.HasOne("JassApp.DataAccess.Tables.CoiffeurSpielrundeTable", null)
                        .WithMany("Trumpfrunden")
                        .HasForeignKey("CoiffeurSpielrundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JassApp.DataAccess.Tables.CoiffeurSpielrundeTable", b =>
                {
                    b.Navigation("JassTeams");

                    b.Navigation("Trumpfrunden");
                });
#pragma warning restore 612, 618
        }
    }
}
